### ISSUE TITLE
Ht210 not loading via TIconnect

### ISSUE THREAD

**Issue by allnotcaps** [utz82/HoustonTracker2#16]
I've been using HT2.0 for a while now (love it!) and was trying to upgrade to HT2.10, but the filetype was incompatible and won't load for some reason. I'm a noob at this so here's a screenshot so you can see what i mean. I'm using a TI83 plus with the TI connect software along with cs7.
![capture](https://cloud.githubusercontent.com/assets/18277093/14271229/99ade310-faab-11e5-87fb-36fdccf9fb14.JPG)

**Comment by utz82** [comment]
Hi there, thanks for reporting! I've already fixed the issue in trunk. So try the latest beta build from the repo ( https://github.com/utz82/HoustonTracker2/blob/master/ht2.8xp?raw=true ), in theory that should work.

**Comment by allnotcaps** [comment]
it loaded up just fine (I had to delete some spaces that were in the filename first). It definitely feels different, with the cursor not moving down after each input (I can get used to that, it makes sharp note input modifications easier). The tempo settings however don't seem much different. it still gets slower as you input higher values and then you only have a handful of useable tempos. I still like it, and will probably crunch a few quick songs tonight with it to see if i notice anything else.

**Comment by utz82** [comment]
The old cursor behaviour can be re-enabled by pressing [MODE] ;)
Tempo settings are indeed unchanged in 2.10. There seems to be quite some demand for more fine-grained tempo control so I'll start thinking about how to implement it. It'll be rather tricky to pull off without increasing row transition noise. The latter issue is quite severe already imo, so fixing that has priority for me atm.

**Comment by allnotcaps** [comment]
sweet. in any case, I kind of like working with the limitations in the meantime. I was curious whether or not you had any information on overclocking the calculator to give more options. i imagine that it would mess with global settings, but it might offer up a bit more control overall. i just came across that as something that people apparently do with these things and figured it might be worth a shot.

**Comment by utz82** [comment]
Overclocking would most likely glitch out the display, because HT's gfx driver is already running at the max of what the LCD controller can handle. So I don't think it's worth it, unfortunately.

**Comment by allnotcaps** [comment]
good to know. any thoughts on underclocking? it's actually an easier procedure.

**Comment by utz82** [comment]
Underclocking should work, but you'll get an increasingly nasty parasite tone if the speed drops by more than ~25%. This is due to how the 1-bit mixing in HT2 works - the parasite tone is actually always there, but normally it's above the range of tones that humans can hear.

**Comment by allnotcaps** [comment]
i actually noticed it when i sampled it out and zoomed in. i imagine you've seen what thw waves from this look like (one of my favorite things about it actually). the interleaving is one thing, but my oscope can pick up some strange fluctuations that are leading me to consider a debounce mod for the day when i put in a legit audio jack.

**Comment by utz82** [comment]
Yeah, there some strange things going on for sure, and I don't fully understand all of it. For one thing, HT 2.00 had an unbalanced sound loop, but that's changed in 2.10 (except when using some of the more obscure drum modes). Also the TI's CPU clock isn't particularly accurate (and getting worse with every new model, it seems).

**Comment by utz82** [comment]
More fine-grained speed control implemented, check it out! The actual range of available tempos is now limited to 0x01-0x3f ticks. If you add 0x40 to the value, the length of the first tick will be reduced by ¾, adding 0x80 will reduce it by ½, and adding 0xc0 will reduce it by ¼. So for example setting the speed to 0x08 will give you a row length of 8 ticks (obviously), 0xc8 will give you 7¾ ticks, 0x88 will give you 7½ ticks, and 0x48 will give you 7¼ ticks. Works with both the global setting and the Fxx command.

**Comment by allnotcaps** [comment]
looks awesome! i'll get it up and running soon. trying to find time between
school work and life to get down on some more TI tracks. I posted an early
demo i made with the 2.0 distro, and i'll have a few new fresh ones up
soon. https://soundcloud.com/adaptr/calculon
